import ast
import json

from odoo import api, models

from .model_retriever import OdooModelRetriever
from .client import client

retriever = OdooModelRetriever()

class OdooAIService(models.AbstractModel):
    _name = "setu.ai.service"
    _description = "Odoo AI Service"

    def validate_query(self, query, relevant_schema):

        query = query.strip()

        if query.startswith("```"):
            lines = query.splitlines()

            if lines[0].startswith("```"):
                lines = lines[1:]

            if lines and lines[-1].strip() == "```":
                lines = lines[:-1]

            query = "\n".join(lines).strip()

        try:
            tree = ast.parse(query, mode="eval")
        except SyntaxError as error:
            raise ValueError(
                f"Invalid Python query generated by AI: {error}"
            )

        expression = tree.body

        if not isinstance(expression, ast.Call):
            raise ValueError(
                "Query must be an Odoo ORM method call."
            )

        method_call = expression

        if not isinstance(method_call.func, ast.Attribute):
            raise ValueError(
                "Invalid ORM method."
            )

        operation = method_call.func.attr

        allowed_operations = {
            "search",
            "search_count",
            "read_group",
        }

        if operation not in allowed_operations:
            raise ValueError(
                f"Operation '{operation}' is not allowed."
            )

        model_access = method_call.func.value
        if not isinstance(model_access, ast.Subscript):
            raise ValueError(
                "Query must use self.env['model']."
            )

        env_object = model_access.value

        if not (
            isinstance(env_object, ast.Attribute)
            and env_object.attr == "env"
        ):
            raise ValueError(
                "Query must use self.env."
            )

        env_owner = env_object.value

        if not (
            isinstance(env_owner, ast.Name)
            and env_owner.id == "self"
        ):
            raise ValueError(
                "Invalid environment access."
            )

        model_node = model_access.slice

        if isinstance(model_node, ast.Constant):
            model_name = model_node.value
        else:
            raise ValueError(
                "Model name must be a string."
            )

        if model_name not in relevant_schema:
            raise ValueError(
                f"Model '{model_name}' was not provided "
                f"by the schema."
            )
        available_fields = (
            relevant_schema[model_name]
            .get("fields", {})
        )

        self._validate_query_fields(
            expression,
            available_fields,
        )

        return True


    def _validate_query_fields(
        self,
        expression,
        available_fields,
    ):

        for node in ast.walk(expression):
            if isinstance(
                node,
                (
                    ast.Import,
                    ast.ImportFrom,
                    ast.Lambda,
                    ast.FunctionDef,
                    ast.ClassDef,
                    ast.Global,
                    ast.Nonlocal,
                    ast.Delete,
                    ast.Await,
                    ast.Yield,
                    ast.YieldFrom,
                ),
            ):
                raise ValueError(
                    "Python code execution is not allowed."
                )

            if isinstance(node, ast.Attribute):

                allowed_attributes = {
                    "env",
                    "search",
                    "search_count",
                    "read_group",
                }

                if node.attr not in allowed_attributes:
                    raise ValueError(
                        f"Attribute '{node.attr}' is not allowed."
                    )

    @api.model
    def execute_my_query(
        self,
        query,
        relevant_schema,
    ):

        self.validate_query(
            query,
            relevant_schema,
        )

        try:
            result = eval(
                query,
                {
                    "__builtins__": {},
                },
                {
                    "self": self,
                },
            )

        except Exception as error:
            raise ValueError(
                f"Unable to execute ORM query: {error}"
            )

        return self._serialize_result(result)

    def _serialize_result(self, result):

        # search_count()
        if isinstance(result, int):
            return result

        # search()
        if hasattr(result, "__iter__"):

            serialized = []

            for record in result:

                if hasattr(record, "_name"):

                    serialized.append({
                        "id": record.id,
                        "name": record.display_name,
                    })

                elif isinstance(record, dict):

                    serialized.append(record)

                else:

                    serialized.append(record)

            return serialized

        return result

    @api.model
    def generate_query(self, question):

        schema_service = self.env[
            "setu.ai.schema"
        ]

        schema = schema_service.get_schema()

        relevant_models = retriever.find_relevant_models(
            question,
            schema,
            top_k=5,
        )

        model_names = [
            item["model"]
            for item in relevant_models
        ]

        relevant_schema = (
            schema_service.get_schema_for_models(
                model_names
            )
        )

        print("QUESTION:", question)

        print("RELEVANT MODELS:")

        for model in relevant_models:
            print(model)

        prompt = f"""
            You are an AI data analyst working with Odoo.
            
            The user asked:
            
            {question}
            
            Here is the relevant Odoo database schema:
            
            {json.dumps(relevant_schema, indent=2)}
            
            Your task is to generate ONE Odoo ORM query
            that can answer the user's question.
            
            IMPORTANT RULES:
            
            1. Generate ONLY an Odoo ORM expression.
            2. Do NOT generate JSON.
            3. Do NOT generate SQL.
            4. Do NOT explain anything.
            5. Do NOT use Python code other than the ORM expression.
            6. Do NOT use sudo().
            7. Do NOT use create().
            8. Do NOT use write().
            9. Do NOT use unlink().
            10. Do NOT use env.cr.
            11. Do NOT use eval().
            12. Do NOT use exec().
            13. Do NOT access the filesystem.
            14. Do NOT import anything.
            
            Allowed ORM methods:
            
            self.env["model"].search(...)
            self.env["model"].search_count(...)
            self.env["model"].read_group(...)
            
            Use ONLY models and fields that exist in the provided schema.
            
            Return ONLY the ORM expression.
            
            Example:
            
            self.env["res.partner"].search_count(
                [("customer_rank", ">", 0)]
            )
            
            Another example:
            
            self.env["product.template"].search(
                [],
                limit=5,
                order="sales_count desc"
            )
            """

        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
        )

        return response.text