from . import teacher
from . import student
from . import subject
from . import school_class
from . import academic_year
from . import class_year
from . import class_subject
from . import class_teacher_assignment
from . import class_subject_teacher
from . import student_enrollment
from . import student_attendance
from . import exam
from . import exam_subject
from . import exam_result